### PR TITLE
added postBody store in advance to add postBody data by exception-controller-spring

### PR DESCRIPTION
**Pull request by michl-b**
Hi Imam,

do you see there any security or privacy issues in this?

### CODE REVIEW

**Review by imamchishty — APPROVED** [review]
1. We might be able to remove/mask secure data from the creators of the exception model, i.e. via the controller.
2. I'm guessing this could be used for POST/PUT etc? If that is the case requestBody might be more appropriate for the field name (however I'm not too fussy).
3. Obtaining the postBody could be done via a filter although the Reader can only be read once so you'd need to 'cache' it somewhere and expose it via maybe a ThreadLocal. This is probably suited for a separate library/component as it's really useful. Drawback of this is that for each request you'll be effectively reading the post data twice. So we should maybe have a property which can disable this feature.

**Comment by imamchishty** [comment]
Nice idea Michael!

**Comment by imamchishty** [comment]
1.0.7 has been released to bintray and maven central.

Versions:
https://github.com/imamchishty/artifact-versions

It might be a good idea to update the other projects, I'll start looking at this.

**Comment by michl-b** [comment]
I think you second point is totally right, I should have named it requestBody.

But I don't understand you third point at the moment. Do you see any issues if we simply read the requestBody by request.getReader().lines() in the ExceptionController if the request was a POST/PUT/DELETE method?

**Comment by imamchishty** [comment]
I don't think you have access to the Reader from the exception controller. By the time it gets to it, it would be empty as it's already been read by the rest controller.

I was suggesting:
1. Add a generic servlet filter (in a new library) that reads the Reader and caches the values. These values are then available via a ThreadLocal.
2. Create a new ExceptionInterceptor (in new library) implementation (see exception-controller-spring). This will use the value from the ThreadLocal and store it into the exception model.
3. Change the execution order in the exception controller. Call the interceptor before the log method is called. Benefit of this way is that the exception controller isn't tied to the generic servlet filter, e.g. from a maven dependency. They all remain loose.

Maybe the trace-request could benefit from this as well?

**Comment by imamchishty** [comment]
exception-controller-spring has been updated to:
1. Updated the exception-core version to 1.0.7.
2. ExceptionInterceptor is called before logging, allowing changes to be made if necessary.
3. Spring boot version updated to 1.4.0.RELEASE.
4. Spring core version updated to 4.3.2.RELEASE.

Released to Maven Central, 1.0.10.

**Comment by imamchishty** [comment]
For current versions:

https://github.com/imamchishty/artifact-versions

**Pull request merged**
